In [87]:
import numpy as np

In [88]:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [89]:
a[:] = 2
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [90]:
b = np.arange(1, 10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
b = b.reshape((3, 3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
a.dtype, b.dtype

(dtype('float64'), dtype('int64'))

In [93]:
aa = np.zeros((3, 3), dtype=np.int64)
aa[:] = 2
aa

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [94]:
aa.fill(8)
aa

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [95]:
aa += 3
aa

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [96]:
# aa /= 3 # The result is a floating point value thus it can't store it again in an int64 bucket
aa

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [97]:
a += 3
a /= 3 # no more errors because we didn't specify the type for variable a thus it became float
a

array([[1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667]])

In [98]:
a.sum()

15.0

In [99]:
a.sum(0) # sum of each columns

array([5., 5., 5.])

In [100]:
b.sum(1) # sum of rows

array([ 6, 15, 24])

In [101]:
b.sum(axis=1)

array([ 6, 15, 24])

In [102]:
b.prod()

362880

In [103]:
b.mean()

5.0

In [104]:
b.max(), b.min()

(9, 1)

In [105]:
b.argmax(), b.argmin() # The index of tha max and min values

(8, 0)

In [106]:
peak_to_peak = b.ptp()
peak_to_peak

8

In [107]:
b.max() - b.min()  # the same as PTP above

8

In [108]:
# flatten arrays

b.reshape(b.size)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
b.size

9

In [110]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
b.ravel() # returns a view despite the .flatten method

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
bb = b.flatten() # a copy
bbr = bb.ravel()
bbr += 2
b, bb, bbr

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [113]:
np.repeat(255, 3)

array([255, 255, 255])

In [114]:
np.repeat(b.flatten(), 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8, 9, 9, 9])

In [115]:
np.repeat(b, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6],
       [7, 7, 7, 8, 8, 8, 9, 9, 9]])

In [116]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8, 9, 9, 9])

In [117]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
np.repeat(b, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

In [120]:
np.unique(np.repeat(b.flatten(), 3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
rb = np.repeat(b, 3, axis=1)
ub = np.unique(rb, axis=1)
rb, ub

(array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
        [4, 4, 4, 5, 5, 5, 6, 6, 6],
        [7, 7, 7, 8, 8, 8, 9, 9, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [124]:
rb = np.repeat(b, 3, axis=0)
ub = np.unique(rb, axis=0)
rb, ub

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [125]:
b, np.diagonal(b)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 5, 9]))

In [126]:
b, np.diagonal(b, offset=1)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([2, 6]))

In [127]:
b, np.diagonal(b, offset=-1)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([4, 8]))

In [128]:
b.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [129]:
type(b.tolist()), type(b)

(list, numpy.ndarray)

In [130]:
b.tofile("/tmp/my-array.txt", sep=",")

In [131]:
np.swapaxes(b, 0, 1) # flip axis 0 with axis 1

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [142]:
np.swapaxes(b, 1, 0) # flip axis 1 with axis 0

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [139]:
b, b.transpose(1, 0) # the same as above swapaxes

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]))

In [138]:
b, b.transpose(0, 1)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [135]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Operations

In [143]:
a, b

(array([[1.66666667, 1.66666667, 1.66666667],
        [1.66666667, 1.66666667, 1.66666667],
        [1.66666667, 1.66666667, 1.66666667]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [144]:
a + b

array([[ 2.66666667,  3.66666667,  4.66666667],
       [ 5.66666667,  6.66666667,  7.66666667],
       [ 8.66666667,  9.66666667, 10.66666667]])

In [145]:
a * b

array([[ 1.66666667,  3.33333333,  5.        ],
       [ 6.66666667,  8.33333333, 10.        ],
       [11.66666667, 13.33333333, 15.        ]])

In [146]:
(a + b - 2 * a) / 4

array([[-0.16666667,  0.08333333,  0.33333333],
       [ 0.58333333,  0.83333333,  1.08333333],
       [ 1.33333333,  1.58333333,  1.83333333]])

In [147]:
b % a

array([[1.        , 0.33333333, 1.33333333],
       [0.66666667, 1.66666667, 1.        ],
       [0.33333333, 1.33333333, 0.66666667]])

In [148]:
a % b

array([[0.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667],
       [1.66666667, 1.66666667, 1.66666667]])

In [152]:
b // a # floor division

array([[0., 1., 1.],
       [2., 2., 3.],
       [4., 4., 5.]])

In [151]:
b / a

array([[0.6, 1.2, 1.8],
       [2.4, 3. , 3.6],
       [4.2, 4.8, 5.4]])

In [154]:
np.floor(b / a)

array([[0., 1., 1.],
       [2., 3., 3.],
       [4., 4., 5.]])

In [155]:
np.matmul(a, b)

array([[20., 25., 30.],
       [20., 25., 30.],
       [20., 25., 30.]])

In [156]:
np.matmul(b, a)

array([[10., 10., 10.],
       [25., 25., 25.],
       [40., 40., 40.]])

In [157]:
a.dot(b)

array([[20., 25., 30.],
       [20., 25., 30.],
       [20., 25., 30.]])

In [158]:
b.dot(a)

array([[10., 10., 10.],
       [25., 25., 25.],
       [40., 40., 40.]])

In [159]:
a @ b

array([[20., 25., 30.],
       [20., 25., 30.],
       [20., 25., 30.]])